### ISSUE TITLE
Text Changes After Pressing Enter

### ISSUE THREAD

**Issue by OpenSyntax5** [ETBCOR/nasin-nanpa#23]
I typed "lipu nasa" and the hit enter. I am using LibreOffice Writer.

https://github.com/user-attachments/assets/a6fa0da0-2aaf-4569-a87f-e55b17058851

**Comment by ETBCOR** [comment]
At first this seemed very mystifying to me, but after watching it a few times, I think I see what's going on! When hitting enter, LibreOffice decided to capitalize `lipu`, which breaks the ligature (all the ligatures only work with lowercase. I think there's an option to disable Auto Capitalize somewhere in LibreOffice. Otherwise, I think you can undo to remove the automatic capitalization. Hope this helps.

**Comment by OpenSyntax5** [comment]
That worked! Thanks! For anyone wondering, to turn off auto capitalize go to Tools > AutoCorrect > AutoCorrect Options > Options and then uncheck "Capitalize first letter of every sentence" in both columns.

**Comment by ETBCOR** [comment]
> Hey! Another Idahoan tokiponist! From Boise btw :)

a, mi lukin ala e ni lon tenpo pini-- ike! sina wile la o toki tawa mi lon ilo Discord a kepeken nimi `etbcor` :)
